# Generated by Django 4.2.6 on 2023-11-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='img/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Rasmla',
            },
        ),
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200, verbose_name='Rasm nomi:')),
                ('body', models.TextField(verbose_name='Rasm texti:')),
                ('image_one', models.ImageField(upload_to='img/', verbose_name='Bitta rasm uchun:')),
                ('f_link', models.URLField(max_length=4000, verbose_name='Facebook link *')),
                ('t_link', models.URLField(max_length=4000, verbose_name='Telegram link *')),
                ('images', models.ManyToManyField(to='news.fotos', verbose_name='Rasmlar:')),
                ('views', models.ManyToManyField(related_name='views', to='news.ipmodel', verbose_name='Korishlar soni')),
            ],
            options={
                'verbose_name': 'Yangilikla',
            },
        ),
    ]
