# Generated by Django 4.2.6 on 2023-11-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='views', to='news.ipmodel', verbose_name='Korishlar soni'),
        ),
    ]
