# Generated by Django 4.2.6 on 2023-11-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotos',
            old_name='image',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='news',
            name='images',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ManyToManyField(related_name='image', to='news.fotos', verbose_name='Rasmlar:'),
        ),
    ]
