# Generated by Django 4.2.6 on 2023-11-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_image_fotos_images_remove_news_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='updated_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
