# Generated by Django 4.2.6 on 2023-11-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image_one',
            field=models.ImageField(default=2, upload_to='new/', verbose_name='bitta rasm*'),
            preserve_default=False,
        ),
    ]
