# Generated by Django 4.2.6 on 2023-11-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_image_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
