# Generated by Django 4.2.6 on 2023-11-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('f_name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('l_name', models.CharField(max_length=100, verbose_name='Familiyasi')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email nomi')),
                ('phone', models.CharField(max_length=20, verbose_name='Boglanish telefoni')),
                ('day_time', models.CharField(max_length=20, verbose_name='Tashrif kuni va soati')),
                ('num_people', models.CharField(max_length=20, verbose_name='Tashrifchila soni')),
                ('obj_name', models.CharField(max_length=20, verbose_name='Muassa nomi')),
                ('type_excursion', models.IntegerField(choices=[(1, 'uz'), (2, 'en'), (3, 'ru'), (4, 'kr')], default=1, verbose_name='ekskursiya turi')),
                ('language_excursion', models.CharField(choices=[('online', 'new'), ('offline', 'rejected')], default='online', max_length=9, verbose_name='ekskursiya tili')),
            ],
            options={
                'verbose_name': 'Boglanish',
            },
        ),
    ]
