# Generated by Django 4.2.6 on 2023-11-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='language_excursion',
            field=models.CharField(choices=[("o'zbekcha", 'new'), ('english', 'rejected'), ('ruscha', 'russion')], default="o'zbekcha", max_length=9, verbose_name='ekskursiya tili'),
        ),
    ]
