# Generated by Django 4.2.6 on 2023-11-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_alter_contact_language_excursion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='day_time',
            field=models.CharField(max_length=20, verbose_name='Tashrif kuni va soati*'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email nomi*'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='f_name',
            field=models.CharField(max_length=100, verbose_name='Ismi*'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='l_name',
            field=models.CharField(max_length=100, verbose_name='Familiyasi*'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='language_excursion',
            field=models.CharField(choices=[("o'zbekcha", 'uz'), ('english', 'en'), ('ruscha', 'ru')], default="o'zbekcha", max_length=9, verbose_name='ekskursiya tili*'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='num_people',
            field=models.CharField(max_length=20, verbose_name='Tashrifchila soni*'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='obj_name',
            field=models.CharField(max_length=20, verbose_name='Muassa nomi*'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Boglanish telefoni*'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type_excursion',
            field=models.IntegerField(choices=[(1, 'Viktorinali'), (2, 'Oddiy'), (3, 'Mobile Ilovali')], default=1, verbose_name='ekskursiya turi*'),
        ),
    ]
