# Generated by Django 4.2.6 on 2023-11-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_alter_contact_day_time_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='language_excursion',
            field=models.CharField(choices=[("o'zbekcha", 'uz'), ('english', 'en'), ('ruscha', 'ru')], default='uz', max_length=9, verbose_name='ekskursiya tili*'),
        ),
    ]
