# Generated by Django 4.2.6 on 2023-11-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True)),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('address', models.CharField(max_length=200, verbose_name='Manzil:')),
                ('phone', models.CharField(max_length=300, verbose_name='Telefon:')),
                ('bus', models.CharField(max_length=100, verbose_name='Transport :')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail:')),
            ],
            options={
                'verbose_name': 'Boglanish:',
            },
        ),
    ]
