# Generated by Django 4.2.6 on 2023-11-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(default=2, upload_to='img/', verbose_name='Manzil rasmi:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
