# Generated by Django 4.2.6 on 2023-11-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_image_alter_contact_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
