# Generated by Django 4.2.6 on 2023-11-22 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200, verbose_name='Kateriya nomi:')),
            ],
            options={
                'verbose_name': 'Kategoriya_',
            },
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=300, verbose_name='Eksponat nomi:')),
                ('year', models.CharField(max_length=40, verbose_name='Eksponat yaratilgan yil:')),
                ('task', models.CharField(max_length=300, verbose_name='Eksponat Vazifasi:')),
                ('image', models.ImageField(upload_to='img/', verbose_name='Rasm joyi:')),
                ('body', models.TextField(verbose_name='Eksponatlar haqida:')),
                ('file', models.FileField(upload_to='', verbose_name='Audio fayl:')),
                ('image_one', models.ImageField(upload_to='image/')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'verbose_name': 'Eksponat_',
            },
        ),
    ]
