# Generated by Django 4.2.6 on 2023-11-29 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_created_at_alter_category_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='cat',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='category.category'),
            preserve_default=False,
        ),
    ]
