# Generated by Django 4.2.6 on 2023-11-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='rasm/')),
            ],
            options={
                'verbose_name': 'Rasm',
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, verbose_name='Muzey nomi')),
                ('body', models.TextField(verbose_name='Muzey haqida')),
                ('images', models.ManyToManyField(related_name='images', to='about.img', verbose_name='Rasmlar')),
            ],
            options={
                'verbose_name': 'Muzey haqida',
            },
        ),
    ]
