# Generated by Django 4.2.6 on 2023-11-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default=2, upload_to='note/', verbose_name='image'),
            preserve_default=False,
        ),
    ]
