# Generated by Django 4.2.6 on 2023-11-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.CharField(max_length=200, verbose_name='Kasbi')),
                ('full_name', models.CharField(max_length=300, verbose_name='Toliq rasm*')),
                ('image', models.ImageField(upload_to='rote/', verbose_name='Rasmi*')),
                ('phone', models.CharField(max_length=200, verbose_name='Telefon raqami*')),
                ('email', models.EmailField(max_length=254, verbose_name='Email nomi*')),
            ],
            options={
                'verbose_name': 'Muzey hodimlari*',
            },
        ),
    ]
