# Generated by Django 4.2.6 on 2023-11-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='road/')),
            ],
            options={
                'verbose_name': 'Muzey tuzimlar',
            },
        ),
        migrations.AlterField(
            model_name='about',
            name='created_at',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='updated_at',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='img',
            name='created_at',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='img',
            name='updated_at',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='created_at',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='updated_at',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
