# Generated by Django 4.2.6 on 2023-11-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_structure_alter_about_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='updated_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='img',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='img',
            name='updated_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leader',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leader',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
